### ISSUE TITLE
Study timer [REQUEST] 

### ISSUE THREAD

**Issue by susuk11** [indifyco/Feature-Requests#54] opened 2021-09-20 19:57 UTC
### What would this widget do?

This would be a widget where you can put a timer to study with. You would set how long you want to study for, how long of a break you want, and the amount of times it would repeat itself.

**Comment by indify-co** [comment] 2021-11-26 22:46
Thanks for the great suggestion! Marking this as a duplicate of #52 - please follow along there for updates :)

**Closed as completed by indify-co** 2021-11-26 22:46 UTC
Labels: widget request
